### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by mariobrussi** [kinderp/humhub-modules-services#1]
I'm looking for a simple guide to install this module, can you provide me one? Thank you in advance

**Comment by kinderp** [comment]
Ciao Mario, il modulo non è ancora pronto. Ci lavoro nel tempo libero (che è molto poco).
Stay tuned ;)

**Comment by mariobrussi** [comment]
Grazie per la risposta :)
Sarebbe il modulo perfetto per i miei scopi,
Buona fortuna per lo sviluppo  :)
